# Generated by Django 3.1.5 on 2021-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210213_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='edit',
            field=models.BooleanField(null=True),
        ),
    ]
